# this file is for my app's url configuration.
# it will contain all the urls for my blog app.

from django.urls import path, include # path is for defining individual url patterns. include allows me to reference other url configurations, making it easier to manage complex url structures.
from rest_framework.routers import DefaultRouter # DefaultRouter automatically creates url patterns for viewsets, simplifying the process of setting up RESTful APIs.
from .views import PostViewSet, CommentViewSet

router = DefaultRouter() # creates an instance of DefaultRouter
router.register(r"posts", PostViewSet) # this line registers the PostViewSet with the router under the prefix "posts". it means that any url starting with "posts/" will be handled by the PostViewSet. the r before the string indicates it's a raw string, which is useful for regex patterns.
router.register(r"comments", CommentViewSet) # automatically generates standard CRUD (create, read, update, delete) endpoints for comments just like it does for posts.

urlpatterns = [ # this list holds all the url patterns for my blog app.
    path("", include(router.urls)), # this line includes all the urls generated by the router at the root url of the blog app. it means that if i navigate to the base url of the blog app, i will have access to all the endpoints defined by the PostViewSet and CommentViewSet.
]
